# Generated by Django 2.0.5 on 2018-05-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('reminder_date', models.DateTimeField()),
            ],
        ),
    ]
