# Generated by Django 2.0.5 on 2018-05-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminder_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
