# Generated by Django 2.0.5 on 2018-05-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180520_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder_date',
            field=models.DateTimeField(),
        ),
    ]
